-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 02:00:16 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LetsRideDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LetsRideDB` ;

-- -----------------------------------------------------
-- Schema LetsRideDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LetsRideDB` DEFAULT CHARACTER SET utf8 ;
USE `LetsRideDB` ;

-- -----------------------------------------------------
-- Table `LetsRideDB`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`country` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`country` (
  `country_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`state` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`state` (
  `state_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(255) NOT NULL,
  `country_id` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`state_id`),
  INDEX `fk_state_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_state_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `LetsRideDB`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`city` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`city` (
  `city_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NOT NULL,
  `state_id` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_state_idx` (`state_id` ASC),
  CONSTRAINT `fk_city_state`
    FOREIGN KEY (`state_id`)
    REFERENCES `LetsRideDB`.`state` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`address` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`address` (
  `address_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `street_address` VARCHAR(255) NOT NULL,
  `city_id` SMALLINT(5) UNSIGNED NOT NULL,
  `postal_code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_address_city_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `LetsRideDB`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`vehicle` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`vehicle` (
  `vehicle_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `license_plate` VARCHAR(10) NOT NULL,
  `make` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `year` YEAR NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`vehicle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`driver` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`driver` (
  `driver_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(10,2) NULL DEFAULT 0,
  `picture` BLOB NULL DEFAULT NULL,
  `address_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `vehicle_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`driver_id`),
  INDEX `fk_driver_address_idx` (`address_id` ASC),
  INDEX `fk_driver_vehicle_idx` (`vehicle_id` ASC),
  CONSTRAINT `fk_driver_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `LetsRideDB`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_driver_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `LetsRideDB`.`vehicle` (`vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`customer` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`customer` (
  `customer_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `picture` BLOB NULL DEFAULT NULL,
  `address_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_address_idx` (`address_id` ASC),
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `LetsRideDB`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`ride`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`ride` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`ride` (
  `ride_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `driver_id` SMALLINT(5) UNSIGNED NOT NULL,
  `customer_id` SMALLINT(5) UNSIGNED NOT NULL,
  `start_addr` VARCHAR(255) NOT NULL,
  `end_addr` VARCHAR(255) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ride_id`),
  INDEX `fk_ride_driver_id_idx` (`driver_id` ASC),
  INDEX `fk_ride_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_ride_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `LetsRideDB`.`driver` (`driver_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ride_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LetsRideDB`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`payment` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`payment` (
  `payment_id` SMALLINT(5) UNSIGNED NOT NULL,
  `amount` DECIMAL(5,2) NULL DEFAULT 0.00,
  `payment_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  CONSTRAINT `fk_payment_ride`
    FOREIGN KEY (`payment_id`)
    REFERENCES `LetsRideDB`.`ride` (`ride_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`rating` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`rating` (
  `rating_id` SMALLINT(5) UNSIGNED NOT NULL,
  `driver_stars` TINYINT(5) NULL DEFAULT 0,
  `driver_comment` VARCHAR(200) NULL DEFAULT NULL,
  `customer_stars` TINYINT(5) NULL DEFAULT 0,
  `customer_comment` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`rating_id`),
  CONSTRAINT `fk_rating_ride`
    FOREIGN KEY (`rating_id`)
    REFERENCES `LetsRideDB`.`ride` (`ride_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LetsRideDB`.`network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LetsRideDB`.`network` ;

CREATE TABLE IF NOT EXISTS `LetsRideDB`.`network` (
  `driver_id` SMALLINT(5) UNSIGNED NOT NULL,
  `driver_lat` FLOAT NOT NULL,
  `driver_lng` FLOAT NOT NULL,
  `customer_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `pickup_lat` FLOAT NULL DEFAULT NULL,
  `pickup_lng` FLOAT NULL DEFAULT NULL,
  `pickup_addr` VARCHAR(255) NULL DEFAULT NULL,
  `dest_lat` FLOAT NULL DEFAULT NULL,
  `dest_lng` FLOAT NULL DEFAULT NULL,
  `dest_addr` VARCHAR(255) NULL DEFAULT NULL,
  `accepted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `ride_fare` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `ride_dur` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`driver_id`),
  INDEX `fk_network_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_network_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `LetsRideDB`.`driver` (`driver_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_network_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LetsRideDB`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
